### ISSUE TITLE
check for right shift and right control

### ISSUE THREAD

**Issue by Aiz0** [SleepyG11/HandyBalatro#1]
Handy currently only checks if lshift or lctrl is down.
This is a problem because the keys i were planning on using are mapped to rshift and rctrl.

you can do this to also check for rshift and rctrl
```lua
love.keyboard.isDown("lshift", "rshift")
love.keyboard.isDown("lctrl", "rctrl")
```

**Comment by SleepyG11** [comment]
Added.
